version: "3.2"
services:
  web:
    hostname: web.dwwm-magento2.local
    image: mflasquin/docker-nginx
    ports:
      - 443:443
      - 80:80
    links:
      - fpm
      - db
      - elasticsearch
    volumes:
      - ../htdocs:/var/www/htdocs
      - ./logs/web:/var/log/nginx
    env_file:
      - ./env/web.env

  fpm:
    hostname: fpm.dwwm-magento2.local
    image: mflasquin/docker-php-fpm:7.4
    tty: true
    links:
      - db
      - maildev:mail
      - elasticsearch
    volumes:
      - ../htdocs:/var/www/htdocs
      - ./logs/php:/var/log/php-fpm
    env_file:
      - ./env/fpm.env

  db:
    hostname: db.dwwm-magento2.local
    image: mysql:8.0.28
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./logs/db:/var/log/mysql
    env_file:
      - ./env/db.env

  cli:
    hostname: cli.dwwm-magento2.local
    image: mflasquin/docker-cli:7.4
    tty: true
    links:
      - db
      - maildev:mail
      - elasticsearch
    volumes:
      - ../htdocs:/var/www/htdocs
    env_file:
      - ./env/cli.env

  maildev:
    image: djfarrelly/maildev
    ports:
      - 8081:80
    command:
      - bin/maildev
      - --web=80
      - --smtp=25

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - "db"